[package]
name = "structopt"
version = "0.2.6"
authors = ["Guillaume Pinot <texitoi@texitoi.eu>"]
description = "Parse command line argument by defining a struct."
documentation = "https://docs.rs/structopt"
repository = "https://github.com/TeXitoi/structopt"
keywords = ["clap", "cli", "derive", "docopt"]
categories = ["command-line-interface"]
license = "Apache-2.0/MIT"
readme = "README.md"

[features]
default = ["clap/default"]
nightly = ["structopt-derive/nightly"]

[badges]
travis-ci = { repository = "TeXitoi/structopt" }

[dependencies]
clap = { git = "https://github.com/guangie88/clap-rs.git", rev = "allow-deprecated", default-features = false }
structopt-derive = { path = "structopt-derive", version = "0.2.6" }

[workspace]
